-   id: minifyall
    name: @josee9988/minifyall
    description: ''
    entry: minifyall
    language: node
    'types': [text]
    args: ["-m -s .min -d web/static"]
    require_serial: false
    additional_dependencies: ["@josee9988/minifyall@1.1.12"]
    minimum_pre_commit_version: '0'
